### ISSUE TITLE
cannot import 'Sequence'

### ISSUE THREAD

**Issue by kallisti5** [matthew-brett/nb2plots#21]
```
$ nb2plots
Traceback (most recent call last):
  File "/home/kallisti5/.local/bin/nb2plots", line 15, in <module>
    from nb2plots.commands import bin_stdout
  File "/home/kallisti5/.local/lib/python3.10/site-packages/nb2plots/__init__.py", line 7, in <module>
    from . import nbplots
  File "/home/kallisti5/.local/lib/python3.10/site-packages/nb2plots/nbplots.py", line 180, in <module>
    from collections import defaultdict, Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by matthew-brett** [comment]
Fixed in 7923488
